# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: 'Build'
on:
  workflow_call:
  workflow_dispatch:
  workflow_run:
    workflows: ["Run Tests"]
    branches: ["master", "main"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    steps:
    - name: Setup
      uses: Kyrasuum/RaylibSetup@v1

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref || github.ref_name }}

    - name: Deps
      run: make dev-deps

    - name: Build
      run: make build

    - name: Archive Production Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-${{ matrix.os }}
        retention-days: 1
        if-no-files-found: ignore
        path: |
          ./bin/
