name: 'Test'

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  gotest:
    runs-on: ubuntu-latest
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for stackhawk/hawkscan-action to upload code scanning alert info
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    steps:
      - name: Setup
        uses: Kyrasuum/RaylibSetup@main

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Deps
        run: make dev-deps

      - name: Test
        run: make test
